import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts';
import '@/app/ui/global.css';
import { SnackbarProvider } from './providers/snackbar-context';
import { TodoListProvider } from './providers/todo-list-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <TodoListProvider>
          <SnackbarProvider>{children}</SnackbarProvider>
        </TodoListProvider>
        <div className="modal-container z-40"></div>
      </body>
    </html>
  );
}
