import type { Metadata } from 'next';

import { inter } from '@/app/fonts';
import '@/app/global.css';
import { Providers } from '@/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Remove the max-w-screen-sm from here when GUI for larger screens are being implemented */}
      <body className={`${inter.className} antialiased max-w-screen-sm mx-auto`}>  
        <Providers>{children}</Providers>
        <div className="modal-container z-40"></div>
      </body>
    </html>
  );
}
